import React,{useEffect,useMemo,useState} from 'react';
import {collection,deleteDoc,doc,getDocs,setDoc} from 'firebase/firestore';
import {auth,db} from './firebase';
import {printRecords,toggleSelection,selectAll} from './recordTools';
const green='#31533a',border='#dfe5dc',bright='#3dad2d';const input={width:'100%',padding:'9px 11px',boxSizing:'border-box',border:`1px solid ${border}`,borderRadius:8};
const btn=(kind='secondary')=>({border:0,borderRadius:8,padding:'9px 12px',fontWeight:800,cursor:'pointer',background:kind==='primary'?bright:kind==='danger'?'#b93333':'#e8eee6',color:kind==='primary'||kind==='danger'?'#fff':green});
const programas=['Toda la mesa','Becas Escolares','Emergencias Médicas','Rehabilitación de Vivienda','Consultorio Dental','Optometría y Oftalmología','Lavandería'];
const blank={email:'',nombre:'',alcance:'Toda la mesa',rol:'Editor',activo:true};
const cols=[{label:'Nombre',key:'nombre'},{label:'Correo',key:'email'},{label:'Alcance',key:'alcance'},{label:'Rol',key:'rol'},{label:'Activo',value:x=>x.activo!==false?'Sí':'No'}];
export default function Accesos(){
 const [rows,setRows]=useState([]),[f,setF]=useState(blank),[msg,setMsg]=useState(''),[editing,setEditing]=useState(null),[selected,setSelected]=useState(new Set());
 async function load(){const s=await getDocs(collection(db,'usuariosNodo'));setRows(s.docs.map(d=>({id:d.id,...d.data()})));}
 useEffect(()=>{load().catch(()=>{});},[]);
 const selectedRows=useMemo(()=>rows.filter(x=>selected.has(x.id)),[rows,selected]);
 async function save(){const email=f.email.trim().toLowerCase();if(!email)return;const oldId=editing;if(oldId&&oldId!==email)await deleteDoc(doc(db,'usuariosNodo',oldId));await setDoc(doc(db,'usuariosNodo',email),{...f,email,actualizadoEn:new Date().toISOString(),otorgadoPor:auth.currentUser?.email||''},{merge:true});setF(blank);setEditing(null);load();setMsg(oldId?'Acceso actualizado.':'Permiso registrado.');}
 function edit(x){setEditing(x.id);setF({...blank,...x});window.scrollTo({top:0,behavior:'smooth'});}
 async function remove(x){if(!confirm(`¿Borrar el acceso de ${x.email}?`))return;await deleteDoc(doc(db,'usuariosNodo',x.id));setSelected(s=>{const n=new Set(s);n.delete(x.id);return n});load();}
 async function removeSelected(){if(!selectedRows.length||!confirm(`¿Borrar ${selectedRows.length} acceso(s)?`))return;for(const x of selectedRows)await deleteDoc(doc(db,'usuariosNodo',x.id));setSelected(new Set());load();}
 return <div><div style={{background:'#fff',border:`1px solid ${border}`,borderRadius:12,padding:16}}><h2 style={{color:green,marginTop:0}}>{editing?'Editar acceso':'Accesos por correo'}</h2><p style={{fontSize:13}}>Otorga acceso a toda la Mesa o únicamente a un programa.</p><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}><input style={input} placeholder="Nombre" value={f.nombre} onChange={e=>setF({...f,nombre:e.target.value})}/><input style={input} placeholder="correo@ejemplo.com" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><select style={input} value={f.alcance} onChange={e=>setF({...f,alcance:e.target.value})}>{programas.map(x=><option key={x}>{x}</option>)}</select><select style={input} value={f.rol} onChange={e=>setF({...f,rol:e.target.value})}><option>Editor</option><option>Captura</option><option>Consulta</option><option>Administrador</option></select></div><label style={{display:'block',marginTop:8,fontSize:13}}><input type="checkbox" checked={f.activo!==false} onChange={e=>setF({...f,activo:e.target.checked})}/> Activo</label><div style={{display:'flex',gap:8,marginTop:10}}><button style={btn('primary')} onClick={save}>{editing?'Actualizar acceso':'Guardar acceso'}</button>{editing&&<button style={btn()} onClick={()=>{setEditing(null);setF(blank)}}>Cancelar</button>}</div>{msg&&<div style={{fontSize:12,marginTop:8}}>{msg}</div>}</div>
 <div style={{display:'flex',gap:8,margin:'12px 0',flexWrap:'wrap'}}><button style={btn()} onClick={()=>setSelected(selected.size===rows.length?new Set():selectAll(rows.map(x=>x.id)))}>{selected.size===rows.length&&rows.length?'Quitar selección':'Seleccionar todos'}</button><button style={btn()} disabled={!selectedRows.length} onClick={()=>printRecords('Accesos NODO',selectedRows,cols)}>Imprimir seleccionados ({selectedRows.length})</button><button style={btn('danger')} disabled={!selectedRows.length} onClick={removeSelected}>Borrar seleccionados</button></div>
 <div style={{display:'grid',gap:8}}>{rows.map(x=><div key={x.id} style={{background:'#fff',border:`1px solid ${border}`,borderRadius:10,padding:12,display:'grid',gridTemplateColumns:'28px 1fr auto',gap:10}}><input type="checkbox" checked={selected.has(x.id)} onChange={()=>setSelected(s=>toggleSelection(s,x.id))}/><div><b>{x.nombre||x.email}</b><div style={{fontSize:12}}>{x.email} · {x.alcance} · {x.rol}</div></div><div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button style={btn()} onClick={()=>edit(x)}>Editar</button><button style={btn()} onClick={()=>printRecords(`Acceso · ${x.email}`,[x],cols)}>Imprimir</button><button style={btn('danger')} onClick={()=>remove(x)}>Borrar</button></div></div>)}</div></div>
}
